name: Algolia Search

on:
  schedule:
    - cron: "0 18 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Ruby Version
      run: ruby --version

    - name: Algolia Index
      env: 
        ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
      run: |
        sudo apt-get -yqq install libpq-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec jekyll build
        bundle exec jekyll algolia
